---
name: iplike-build
run-name: Build PostgreSQL iplike extension
on:
  push:
  workflow_dispatch:

## Build and create the project on every push to the project
jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        pg_version: [ 13, 14, 15, 16, 17, 18 ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/${{ github.repository_owner }}/iplike-builder:0.0.1.b838083
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Update generated configuration files
        run: |
          autoreconf -fvi
      - name: Configure and build from source
        run: |
          ./configure --with-pgsql=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config
          make
      - name: Create Debian packages
        run: |
          dpkg-buildpackage
      - name: Collect Debian build artifacts
        run: |
          mkdir -p debian/artifacts
          mv ../iplike-pgsql* debian/artifacts
      - name: Persist Debian build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iplike-pgsql-${{ matrix.pg_version }}-deb
          path: debian/artifacts/*
      - name: Create RPM packages
        run: |
          make rpm
      - name: Collect RPM build artifacts
        run: |
          mkdir -p rpm/artifacts
          mv "${HOME}/rpmbuild" rpm/artifacts
      - name: Persist RPM build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iplike-pgsql-${{ matrix.pg_version }}-rpm
          path: rpm/artifacts/*
      - name: Release ${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            rpm/artifacts/rpmbuild/RPMS/**
            debian/artifacts/*.deb
